// <auto-generated />
namespace OPIDDaily.DataContexts.OPIDDailyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Nullable_RCheck_DOB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullable_RCheck_DOB));
        
        string IMigrationMetadata.Id
        {
            get { return "202001262106164_Nullable_RCheck_DOB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
