// <auto-generated />
namespace OPIDDaily.DataContexts.OPIDDailyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ColorCoding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColorCoding));
        
        string IMigrationMetadata.Id
        {
            get { return "202004241959520_ColorCoding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
